[google_service_account]
type = "service_account"
project_id = "meterreplacementapp-466911"
private_key_id = "a97b164384349635142b7022d6c47ccb7104d835"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDEt2/mf2hCc8Mg
u2BF0RupObuaAWVtLILDErRMdRVCopPvVjteusLmRQtDbMJ9xyODWVYH/jvmQOUL
Ny+S26iGulV97qa6QDaFLOuy6q49vEx/w5Z1NFjYSffIymY+Z488EeMrqpPyJSYU
xoofQd3ixI+ESmVtTm5BXfurpVWKUSUWCCbmKQEYQL3qq6hYi9Bwo/E1BF4Kwc5b
ik1moYXxJbIy+01y2mimA5Cbqs+mZyrqZ8CTfPVuJc5HmBAs3xylCp/eYjlo9pXe
1eEQM42cEuoncl/R5N+QFHL73j2g105XoTKN68m9xDrAX4787C22GiAqbP31qWaV
MwE7eBmFAgMBAAECggEAAMq1CM18fIzKVuH9ZwQkQ1y37f/Eo7+pHkkZMEsywbW1
a+8B7PiwriXOMzN6rCNWd9t7mcUJNeN1Yin5TaY6s6G7Lfcwjp4rJtAU4GYXbqiV
k9h6s5AS+q1/8aJdVP6S65/6zrZjqaoPapTKzr0AiQtXgVkEHYBSUbFwjbLsEp/Z
/C+Lmq3GOx4FGIpWigaXM7Sxt+IexAUgppus5YbVPq7yHBB/LBMg3lc+O9Z1Cw51
qMLpMlJ6LMTX/ju2kLW4Pm3ubGQQ6D2d+WBSwKY1FgNzhF+76jsVxEWYfYPB5Fi/
XGGbOeUHr4BU8B3hNLOa8L7sPHcAt6tZNwOYcUZnxQKBgQDob9IojQm4xn62oVtc
L4EGxr0kDPh0250kFSrBaD2zO+eC82MUPYjyg0th7OtAIU3SRsZ1dpDxqBMKN9Ti
LDjrbwshqZkR0S04+xTWvghrEzg9RWfO0AuADo6MGNfb5KjpZPdPkmMir4gL8XLM
/c/uYu/qt7TJ0+tvzqFvCNVTewKBgQDYqJuCsRBs6a2i+3O89a1nwCDPUC9hk2U6
J8d5v2FT20sARQXYxmWzmAiPEKx2LakNUDOs5oGPqk0HVbl6D+ZJIgf7Rfj/s51K
dTlxaFVQg0lfOVSfA/vsQqzzM4ZHPQQsWAIwUzTTkWuyKGGsRulbIHJtKbSIfUlu
LNeU2Lo2/wKBgQDXGOP68snUXJxWlevd23gjtTbDbd1fBvzcr1npsXWnsAAGhwVh
bbCV/Dp+XKk3p5pExYpSmW54s3krM4+l3hauiQxcEn68pj6bRH98Wk+gByE8UkZG
dPCviMkRjMv1ih1mHzFeSbHEH3xe0QnT+e26RYSQSYDcZWizBx0Ni7cekQKBgGm4
JGHqWpR6liLARiJ/UwUcSCZA/03CqZNuE7UBwNE1YWyZQZgcf0XaOtrsjOsBrsrz
RrPoqnHa7MlWeDHqjjlDZNektjK3h1nsx4HiIjcuSOAxTmxlekk348KscqpSSLYG
n9LK1y0heYauk7KHy5iOxackwZYUZH9hXDSiaIMrAoGBAItPpGj4oRh76y7C7bBX
nXa4h09alk1HcaF+4DUOox+HCdMIAFzWNaHjCUexOwTINUwiJO1vtZ5sqKVVVc0O
hCU2GOOFiK6CUiQqqHc8VTK++R4uYSMGaxE/n22kYiouU8gbzFwA6/f20GNy8VyU
t346b4lUMPWaFJNP80pvbJwY
-----END PRIVATE KEY-----"""
client_email = "streamlit-meter-bot@meterreplacementapp-466911.iam.gserviceaccount.com"
client_id = "100474983737291469298"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-meter-bot%40meterreplacementapp-466911.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

