[google_service_account]
type = "service_account"
project_id = "meterreplacementapp-466911"
private_key_id = "731249f0190dcd7b5c533e491fd1612a12823817"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCsZJw9DXdY6L7p
sQJYOaJVGm3u9UZym3t3GPssSvbfZGaHDTUyCRWv77tZjZ2bMW7nFNRGLziomCJ0
JzKDrBhb71UnOnZv5reotDgkVk/6Frui8d/qazD34tJGxsyReuZrFN5bxJr1Ke7I
1bN0fiHgjJg/q7rJYiWx2aF6cGsDASzc9iEi1u9IlNQNJIunkfpMT2Pfe7GfoLEQ
NJQ7lP8ad9FytwoZjmT8kmsNPg2KhBFwlwGCjgRPvIbQtk/MzszBQMbwvZtwq3Ot
wMIPFHvcNw50TJwHr7scvKUjBD9bOzhuKyqLz+GrF3t5OValn1Gu4fR6Ml1f9rm6
g56UGC6xAgMBAAECggEATfU3dCJ1UJb70okR4ty5TJvlj9SKFYS7SgnZd9e0mSP5
e2QdJLHYBVY3VlGErqwll0kjj1OGXzNhDT62iLXX1CdATjuRWJwwfJF2+/OuOg1y
r8aKeCMeI1MGvSvkUXuO3Gi0/zHC01Axo8+D1g+9+SILLWvWzX/dRPaCH/Dba6Er
6X5p1yH/S7WA9bAG7OJefKVM1aGezpaBx9Dcv13tJAvd0Pcg3mK7tcTqu0bV66Wy
VZRd/NEYoe2trSACci7Z8ul3nv6IUrJgdQTfIc93lAi2JkbaYHplp7RC08fOC25X
7qsLkQWl9DFS+Ct64T1vnFLUNKUAUccQSX00bEjhywKBgQDUfcUsQKJoo4JkjUsr
DzIuTbJb5q6Z7AYMdAgcz5vMKhoS2YkNqqCS+tgeZ/kGCt9ZH3KiUcilO6brpmrE
GuhJl4OPoAreBP/N9Wy4OFDPBFYM1F6vnFSYbQq9QhaA0SgWz7/fOf99qHTNgdii
EIavnVPTAS6phCBCuhwjC19Y0wKBgQDPsP6ch4rLU/wLXbhz3yWn1fb+/SwfwTTK
CSQLPM3csW3/g60CXhRmsDFM/mZ2ATDXZxkeydBga+QqZvVJOU+58WTp8wffj280
uRTNe9F/NopNBYZxfB63Q2fJhAWFmrH46YOEd85wTbS1wOcU/CClZ6jGPz7+fRas
wnuZ6OCn6wKBgB4JaUXIHS0Nb/Emx+leTImfEgdLpIK9il1YSY1JC4zgpq7jcSwt
YmVkcAhcSidAgjHm8B1h0isJM5879vuhkhRVBpPW27JmooJKnwOrckDRLBjELF5G
iu7A+zOlk+jBqBkRZN35JNRua5RhNm4yR9erNZ4uHJp5wtWr2S5a/S9hAoGAc/QA
Ion17lDkPcBEU8S4tDxb2r6kHNJ0U3vI+NEoqdcRb38nX1QBFde2nqLFt4owp4Hy
32KTCNITn6y9svThUxG3YnoB4kmlL41JVPOU4e4kRp4YElHWoEBsuHAR2SalyC8u
8w0kX0Sy6GpbWTbuTwpRiuUSmWhi+W7XLPV8P6MCgYEAvX6U9NPBEN0l96c1anaB
nRoP9UU8660sAvkZbRIerxIEnt7dkqP38j11Z16H7dPczCkAgtSNREkgFB0e38i5
D1KX4XIg4PSpdRjHbf1gyPy5TZCpKXWHnbt3NABwGe1Tcf8LToyjqhW1JSO1lh08
o12Rs2XJJeqT1rgTE/0JCcw=
-----END PRIVATE KEY-----"""
client_email = "streamlit-meter-bot@meterreplacementapp-466911.iam.gserviceaccount.com"
client_id = "100474983737291469298"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-meter-bot%40meterreplacementapp-466911.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
